# Generated by Django 3.2.7 on 2022-10-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=25)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('avatar', models.FileField(upload_to='')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('M', 'Female')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.TextField(max_length=500)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.pet')),
            ],
        ),
    ]
